Базовая имплементация
urfu-2017/webdev-task-8 pull request #11
Opened 2018-05-03 11:02 UTC by Edheltur

2018-05-03 11:02 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-15 06:21 UTC, savichev-igor commented
🍪

2018-05-15 06:21 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-15 17:42 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-15 17:46 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-15 17:48 UTC, Edheltur commented
https://edheltur.github.io/webdev-task-8/

2018-05-15 17:49 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-18 20:36 UTC, evgenymarkov requested changes

2018-05-18 20:36 UTC, evgenymarkov commented on scale-builder.js
> +            if (periods && periods.length === 0 || periods[periods.length - 1].length !== 1) {
Консоль взрывается от ошибок
![2018-05-19_01-12-58](https://user-images.githubusercontent.com/16443248/40255841-fc195b34-5b01-11e8-8565-0062a6a4cf7b.png)

2018-05-19 05:57 UTC, honest-hrundel commented
:green_apple: Пройден линтинг и базовые тесты

2018-05-19 05:58 UTC, evgenymarkov commented
В остальном всё ок)

2018-05-19 05:58 UTC, evgenymarkov commented
🍏

2018-05-19 05:58 UTC, closed without merging